### ISSUE TITLE
SageMaker Inference Endpoint does not support cuda12

### ISSUE THREAD

**Issue by zhangzhao2010** [qingyuan18/ComfyUI-on-SageMaker#1]
根据sagemker文档显示，inference endpoint 实例的nivida driver版本如下：

Service | GPU | Driver version | Instance types
-- | -- | -- | --
Real-time | NVIDIA | 470.57.02 | ml.p2.*, ml.p3.*, ml.p4d.*, ml.p4de.*, ml.g4dn.*, ml.g5.*
535.54.03 | ml.p5.*
Batch | NVIDIA | 470.57.02 | ml.p2.*, ml.p3.*, ml.p4d.*, ml.p4de.*, ml.g4dn.*, ml.g5*
Asynchronous Inference | NVIDIA | 470.57.02 | ml.p2.*, ml.p3.*, ml.p4d.*, ml.p4de.*, ml.g4dn.*, ml.g5*
535.54.03 | ml.p5.*

https://docs.aws.amazon.com/sagemaker/latest/dg/inference-gpu-drivers.html

而cuda12需要driver版本>=525.60.13，所以dockerfile中安装torch时使用cu121会出现问题，目前最高可使用cu118

所以需要修改dockerfile中的相关语句为以下：
####upgrade torch/torchversion/cuda118 relevant dependence
RUN pip install torch torchvision --upgrade --index-url https://download.pytorch.org/whl/cu118

**Comment by qingyuan18** [comment]
hello @zhangzhao2010 
Thanks for your comment

yes we have already found that compatible issue about cuda/pytorch version before， that's why we are using dockerfile-simple instead with the build script  which use  nvidia's docker images :

FROM nvcr.io/nvidia/pytorch:23.05-py3

thanks again  :)

**Comment by qingyuan18** [comment]
problem solved , hence close the ticket
